### ISSUE TITLE
initial code

### ISSUE THREAD

**Issue by jgallen23** [firstandthird/eslint-config-firstandthird#1]
lets create a eslint config file that will enforce our coding structure.  We originally had a jscs file, but it seems like eslint has become the standard.  We might be able to just inherit from one of the major players and tweak as necessary. I like the [airbnb](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb) one personally, but we can all discuss

**Comment by jgallen23** [comment]
cc @dawnerd @ecwillis @orthagonal

**Comment by jgallen23** [comment]
here is airbnb's es6 styleguide: https://github.com/airbnb/javascript

es5: https://github.com/airbnb/javascript/tree/master/es5

anything you guys disagree with?

**Comment by dawnerd** [comment]
I feel like we're already following airbnb pretty closely, so works for me!

**Comment by jgallen23** [comment]
yeah, and nice that they already have es6 stuff set up.  should we just use theirs or have ours extend theirs?

**Comment by dawnerd** [comment]
Played around with it a bit and theirs is pretty good out of the box EXCEPT they expect you to use babel on everything. I don't think thats really necessary for node code so I made these additions:

```
"ecmaFeatures": {
    "modules": false
  },
  "rules": {
    "comma-dangle": 0,
    "strict": [2, "global"]
  }
```
