### ISSUE TITLE
upgrade to eslint 2.0

### ISSUE THREAD

**Issue by jgallen23** [firstandthird/eslint-config-firstandthird#7]
http://eslint.org/blog/2016/02/eslint-v2.0.0-released

* pull in rules from airbnb and remove dependency
* review new rules from v2 and see if we want to adapt any of them

**Comment by dawnerd** [comment]
Latest airbnb config uses eslint2 now.

**Comment by jgallen23** [comment]
should we stick with their config then?

**Comment by dawnerd** [comment]
I would, less work for us whenever eslint updates. All of the new rules seem reasonable enough to keep - and thanks to your last change we don't even have to do anything!

**Comment by jgallen23** [comment]
one thing I noticed is that it doesn't warn on `function {name}() { }` - non-anonymous functions. Maybe we should add that
